navbar:
  title: Kuressaare Ametikool
  user: Mati Mäetalu
config: true
help: true
title: Päevik
alert: It's okay!
exports:
  - PDF
  - Excel
menu:
  - Kasutaja
  - Seadistused
  - Välju
filters:
  fields:
    - type: radios
      options:
        - Minu tunnid
        - Kõik
    - type: select
      options:
        - Multimeedia kujundajad
        - Teabegraafikud
    - type: text
      label: First
    - type: text
      label: Second
  title: Filtreeri
  menu:
    - Laiendatud filter...
    - Jäta filter meelde
    - --
    - Puhasta filter
actions_top:
  primary:
    - Add
actions_bottom:
  primary:
    - Save
  secondary:
    - Share
    - Assign
  danger:
    - Delete
table:
  headers:
    - Name
    - Group
    - Grade
  rows:
    - 
      - Viirpuu, Silja
      - Tummar, Kalle
      - Kask, Kerli
    - 
      - Lähetusel
      - Tööl
      - Tööl
  actions:
    - Edit
modal:
  title: Hello world
  table: 
    headers:
      - Name
      - Group
      - Grade
    rows:
      - 
        - Viirpuu, Silja
        - Lähetusel
        - 10 EKAP
      - 
        - Rohumaa, Janno
        - Tööl
        - 5 EKAP
    actions:
      - Edit
  actions_bottom:
    primary:
      - Save