navbar:
  title: Kuressaare Ametikool
  user: Mati Mäetalu
config: true
help: true
title: Päevik
alert: It's okay!
exports:
  - PDF
  - Excel
menu:
  - Kasutaja
  - Seadistused
  - Välju
filters:
  radios:
    - Minu tunnid
    - Kõik
  select:
    -
      - Multimeedia kujundajad
      - Teabegraafikud
  text:
    - First
    - Second
  title: Filtreeri
  menu:
    - Laiendatud filter...
    - Jäta filter meelde
    - Puhasta filter
actions_top:
  secondary:
    - Add
actions_bottom:
  primary:
    - Save
  secondary:
    - Share
    - Assign
  danger:
    - Delete
table:
  headers:
    - Name
    - Group
    - Grade
  rows:
    - 
      - 1
      - 2
      - 3
    - 
      - a
      - b
      - c
  actions:
    - Edit
modal:
  title: Hello world
  actions:
    primary:
      - Save